// prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const PRESETS = [
  {
    name: "Karl",
    displayName: "Karl",
    isPremium: false,
    category: "trend",
    sortOrder: 1,
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSize: 36,
    textColor: "#FFFFFF",
    highlightColor: "#FF6B00",
    shadowEnabled: true,
    shadowColor: "#000000",
    outlineEnabled: true,
    outlineColor: "#000000",
    outlineWidth: 2,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
  {
    name: "Hormozi",
    displayName: "Hormozi 2",
    isPremium: false,
    category: "trend",
    sortOrder: 2,
    fontFamily: "Oswald",
    fontWeight: 700,
    fontSize: 38,
    textColor: "#FFFF00",
    highlightColor: "#FFFFFF",
    shadowEnabled: true,
    shadowColor: "#000000",
    outlineEnabled: true,
    outlineColor: "#000000",
    outlineWidth: 3,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
  {
    name: "Matt",
    displayName: "Matt",
    isPremium: false,
    category: "clean",
    sortOrder: 3,
    fontFamily: "Inter",
    fontWeight: 700,
    fontSize: 32,
    textColor: "#FFFFFF",
    highlightColor: "#3B82F6",
    shadowEnabled: true,
    shadowColor: "#000000",
    outlineEnabled: false,
    outlineColor: "#000000",
    outlineWidth: 0,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
  {
    name: "Bob",
    displayName: "Bob",
    isPremium: false,
    category: "bold",
    sortOrder: 4,
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSize: 40,
    textColor: "#FFFFFF",
    highlightColor: "#22C55E",
    shadowEnabled: true,
    shadowColor: "#000000",
    outlineEnabled: true,
    outlineColor: "#000000",
    outlineWidth: 2,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
  {
    name: "Kendrick",
    displayName: "Kendrick",
    isPremium: false,
    category: "trend",
    sortOrder: 5,
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSize: 36,
    textColor: "#FFFFFF",
    highlightColor: "#10B981",
    shadowEnabled: true,
    shadowColor: "#000000",
    outlineEnabled: true,
    outlineColor: "#000000",
    outlineWidth: 2,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
  {
    name: "Doug",
    displayName: "Doug",
    isPremium: false,
    category: "minimal",
    sortOrder: 6,
    fontFamily: "Bebas Neue",
    fontWeight: 400,
    fontSize: 44,
    textColor: "#FFFFFF",
    highlightColor: "#F59E0B",
    shadowEnabled: false,
    shadowColor: "#000000",
    outlineEnabled: true,
    outlineColor: "#000000",
    outlineWidth: 1,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
  {
    name: "Sara",
    displayName: "Sara",
    isPremium: true,
    category: "elegant",
    sortOrder: 7,
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: 32,
    textColor: "#FAFAFA",
    highlightColor: "#EC4899",
    shadowEnabled: true,
    shadowColor: "#000000",
    outlineEnabled: false,
    outlineColor: "#000000",
    outlineWidth: 0,
    positionX: 50,
    positionY: 55,
    animationType: "karaoke",
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Upsert presets
  for (const preset of PRESETS) {
    await prisma.preset.upsert({
      where: { name: preset.name },
      update: preset,
      create: preset,
    });
    console.log(`✅ Preset: ${preset.displayName}`);
  }

  console.log("🎉 Seed completed!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
